import { Silkscreen } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import Footer from "@/components/Footer";

const silkscreen = Silkscreen({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-silkscreen",
});
const mona = localFont({
  src: "../fonts/Mona-Sans.ttf",
  display: "swap",
  variable: "--font-mona",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${silkscreen.variable} relative overflow-x-hidden ${mona.className}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
